name: CD
on: 
  push:
    branches:
      - 'develop'
    paths:
      - 'testing/**'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: TF Plan
      id: tf-plan
      working-directory: 'infrastructure'
      run: |
        terraform init && terraform plan


    - name: TF Applyenv
      id: tf-apply
      working-directory: 'infrastructure'
      if: ${{ steps.tf-plan.outcome }} == 'success'
      run: |
        terraform apply -auto-approve
        echo *:: set-output name=eb_app::$(terraform output eb_application | xargs)*
        echo *:: set-output name=eb_env::$(terraform output eb_environment | xargs)*

    - name: EB Install
      id: eb-install
      uses: sparkplug-app/install-eb-cli-action


    - name: EB Deploy
      id: eb-deploy
      working-directory: 'deployment'
      run: |
          eb init -p docker -r us-east-1 ${{ steps.tf-apply.outputs.eb_app }}
          eb create ${{ steps.tf-apply.outputs.eb_env }}
  


